version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: odsgeo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: odsgeo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odsgeo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: odsgeo-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@odsgeo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - odsgeo-network

  redis:
    image: redis:alpine
    container_name: odsgeo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - odsgeo-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  odsgeo-network:
    driver: bridge 